#syntax=docker/dockerfile:1

FROM oven/bun:1 AS pruner

WORKDIR /repo 

COPY ..

RUN bunx turbo prune hooks-api --docker 


FROM oven/bun:1 AS installer

WORKDIR /repo 

COPY --from=pruner /repo/out/json/ . 

RUN bun install --frozen-lockfile

COPY --from=pruner /repo/out/full/ .

RUN bunx turbo build --filter=hooks-api...

FROM node:22-alpine AS runner

WORKDIR /app 

ENV NODE_ENV=production

COPY --from=installer /repo/apps/hooks-api ./apps/hooks-api
COPY --from=installer /repo/packages ./packages 
COPy --from=installer /repo/node_modules ./node_modules


WORKDIR /app/apps/hooks-api
CMD ["node", "dist/index.js"]
