# syntax=docker/dockerfile:1


FROM oven/bun:1 AS pruner

WORKDIR /repo

COPY . .

RUN bunx turbo prune api --docker


FROM oven/bun:1 AS builder

WORKDIR /repo

COPY --from=pruner /repo/out/json/ .

RUN bun install --frozen-lockfile

COPY --from=pruner /repo/out/full/ .

RUN bunx turbo build --filter=api...

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /repo/apps/api ./apps/api
COPY --from=builder /repo/packages ./packages
COPY --from=builder /repo/node_modules ./node_modules

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["node", "dist/main.js"]

